export const FETCHING_ORDER = 'FETCHING_ORDER';
export const FETCHING_ORDER_SUCCESS = 'FETCHING_ORDER_SUCCESS';
export const FETCHING_ORDER_ERROR = 'FETCHING_ORDER_ERROR';

export const UPDATE_ORDER = 'UPDATE_ORDER';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
export const UPDATE_ORDER_ERROR = 'UPDATE_ORDER_ERROR';

export const CANCEL_ORDER = 'CANCEL_ORDER';
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS';
export const CANCEL_ORDER_ERROR = 'CANCEL_ORDER_ERROR';
