export const FETCHING_RESTAURANT = 'FETCHING_RESTAURANT';
export const FETCHING_RESTAURANT_SUCCESS = 'FETCHING_RESTAURANT_SUCCESS';
export const FETCHING_RESTAURANT_ERROR = 'FETCHING_RESTAURANT_ERROR';

// menu
export const FETCHING_MENU = 'FETCHING_MENU';
export const FETCHING_MENU_SUCCESS = 'FETCHING_MENU_SUCCESS';
export const FETCHING_MENU_ERROR = 'FETCHING_MENU_ERROR';

// food
export const UPDATE_FOOD = 'UPDATE_FOOD';
export const UPDATE_FOOD_SUCCESS = 'UPDATE_FOOD_SUCCESS';
export const UPDATE_FOOD_ERROR = 'UPDATE_FOOD_ERROR';

export const CREATE_FOOD = 'CREATE_FOOD';
export const CREATE_FOOD_SUCCESS = 'CREATE_FOOD_SUCCESS';
export const CREATE_FOOD_ERROR = 'CREATE_FOOD_ERROR';

export const CREATE_DISH_TYPE = 'CREATE_DISH_TYPE';
export const CREATE_DISH_TYPE_SUCCESS = 'CREATE_DISH_TYPE_SUCCESS';
export const CREATE_DISH_TYPE_ERROR = 'CREATE_DISH_TYPE_ERROR';
