export const FETCHING_USER_INFO = 'FETCHING_USER_INFO';
export const FETCHING_USER_INFO_ERROR = 'FETCHING_USER_INFO_ERROR';
export const FETCHING_USER_INFO_SUCCESS = 'FETCHING_USER_INFO_SUCCESS';

export const CREATE_RESTAURANT = 'CREATE_RESTAURANT';
export const CREATE_RESTAURANT_SUCCESS = 'CREATE_RESTAURANT_SUCCESS';
export const CREATE_RESTAURANT_ERROR = 'CREATE_RESTAURANT_ERROR';

export const GET_CURRENT_LOCATION = 'GET_CURRENT_LOCATION';
